import { AITool, IslamicBook, QuranResource, DuaItem, IslamicArticle, PromptItem, QuranVideoRecitation } from '../types';

export const INITIAL_AI_TOOLS: AITool[] = [
  // --- AI VIDEO TOOLS ---
  {
    id: 'google-veo',
    name: 'Google Veo / Flow',
    category: 'video',
    shortDescription: 'Generates high-definition, cinematic 1080p video clips from text or image prompts.',
    longDescription: 'Google Veo is a generative video model capable of creating high-definition videos with remarkable temporal consistency, expressive camera controls, and high photorealism.',
    pricing: 'Free Credits',
    pricingDetail: 'Free trial credits available via Google AI Studio / Flow',
    url: 'https://aitestkitchen.withgoogle.com/tools/video-fx',
    features: ['Text to video', 'Image to video', 'Cinematic AI videos', '1080p resolution'],
    isFeatured: true,
    rating: 4.9,
  },
  {
    id: 'runway-gen3',
    name: 'Runway',
    category: 'video',
    shortDescription: 'Next-generation AI video generation, motion control, and professional editing tools.',
    longDescription: 'Runway Gen-3 Alpha enables unprecedented creative control over camera movement, timing, and hyper-realistic video syntheses.',
    pricing: 'Free Credits',
    pricingDetail: '125 free one-time credits upon signup',
    url: 'https://runwayml.com',
    features: ['AI video generation', 'Video editing', 'Motion brush', 'Camera control'],
    isFeatured: true,
    rating: 4.8,
  },
  {
    id: 'pika-art',
    name: 'Pika',
    category: 'video',
    shortDescription: 'Idea-to-video platform with text-to-video, image-to-video, and 3D animation effects.',
    longDescription: 'Pika allows creators to animate static images, alter specific regions of video, and produce highly creative short clips with simple text inputs.',
    pricing: 'Free Credits',
    pricingDetail: 'Daily free video generation credits',
    url: 'https://pika.art',
    features: ['Text to video', 'Image to video', 'Sound effects AI', 'Region edit'],
    isFeatured: false,
    rating: 4.7,
  },
  {
    id: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    category: 'video',
    shortDescription: 'Next-gen AI model for producing physically accurate, high-speed cinematic shots.',
    longDescription: 'Luma Dream Machine turns text and photos into stunning, fluid 5-second video clips with realistic physics and seamless camera motion.',
    pricing: 'Free Credits',
    pricingDetail: '30 free video generations per month',
    url: 'https://lumalabs.ai/dream-machine',
    features: ['AI cinematic videos', 'Realistic physics', '3D motion smoothness', 'High speed'],
    isFeatured: true,
    rating: 4.8,
  },
  {
    id: 'kling-ai',
    name: 'Kling AI',
    category: 'video',
    shortDescription: 'Ultra-realistic AI video generator creating up to 2-minute high-frame-rate videos.',
    longDescription: 'Kling AI delivers motion simulation with 3D face and body reconstruction, producing smooth, lifelike movement and complex physical interactions.',
    pricing: 'Free Plan',
    pricingDetail: 'Daily login free credits available',
    url: 'https://klingai.com',
    features: ['Realistic AI videos', 'Up to 1080p output', 'Complex physics', 'Long video support'],
    isFeatured: false,
    rating: 4.7,
  },
  {
    id: 'capcut-ai',
    name: 'CapCut AI',
    category: 'video',
    shortDescription: 'User-friendly video editor equipped with AI script generators, auto-captions, and visual filters.',
    longDescription: 'CapCut offers built-in AI video creation tools including automatic subtitle generator, AI background removal, text-to-speech, and auto video editing.',
    pricing: 'Free Plan',
    pricingDetail: 'Generous free tier with optional pro features',
    url: 'https://www.capcut.com',
    features: ['AI editing and effects', 'Auto captions', 'AI avatars', 'Mobile friendly'],
    isFeatured: false,
    rating: 4.9,
  },
  {
    id: 'canva-ai-video',
    name: 'Canva AI Video',
    category: 'video',
    shortDescription: 'Simple drag-and-drop AI video maker for social media, presentations, and clips.',
    longDescription: 'Create videos effortlessly using Magic Design for Video. Converts photos and written concepts into ready-to-publish branded video content.',
    pricing: 'Free Plan',
    pricingDetail: 'Free forever with 50 monthly AI queries',
    url: 'https://www.canva.com/create/videos/',
    features: ['Simple AI video creation', 'Templates library', 'Magic Media', 'No experience needed'],
    isFeatured: false,
    rating: 4.8,
  },

  // --- AI IMAGE TOOLS ---
  {
    id: 'chatgpt-image-dalle',
    name: 'ChatGPT Image Generator',
    category: 'image',
    shortDescription: 'Create detailed custom artwork and graphics powered by OpenAI DALL-E 3.',
    longDescription: 'Integrated into ChatGPT, DALL-E 3 understands nuanced prompts, accurate text rendering inside images, and versatile artistic styles.',
    pricing: 'Free Plan',
    pricingDetail: 'Free users receive limited daily DALL-E image generations',
    url: 'https://chatgpt.com',
    features: ['Text to image', 'Exact prompt following', 'In-chat editing', 'High resolution'],
    isFeatured: true,
    rating: 4.9,
  },
  {
    id: 'google-gemini-imagen',
    name: 'Google Gemini Image Generation',
    category: 'image',
    shortDescription: 'Fast, high-fidelity image creation powered by Google Imagen 3 technology.',
    longDescription: 'Imagen 3 delivers clear lighting, rich textures, sharp photorealism, and clean text layout rendering directly inside Gemini.',
    pricing: 'Free Plan',
    pricingDetail: '100% free with standard Google account',
    url: 'https://gemini.google.com',
    features: ['Photorealistic images', 'Fast generation', 'Prompt assistance', '100% free'],
    isFeatured: true,
    rating: 4.9,
  },
  {
    id: 'meta-ai-imagine',
    name: 'Meta AI Image Generator',
    category: 'image',
    shortDescription: 'Real-time text-to-image generator with animate features across WhatsApp and web.',
    longDescription: 'Meta Imagine generates vibrant visual concepts instantly as you type, with one-click GIF animation options.',
    pricing: 'Free Plan',
    pricingDetail: 'Free to use on web and Meta platforms',
    url: 'https://www.meta.ai',
    features: ['Real-time generation', 'Image animation', 'Vibrant artwork', 'Free access'],
    isFeatured: false,
    rating: 4.6,
  },
  {
    id: 'ideogram-ai',
    name: 'Ideogram',
    category: 'image',
    shortDescription: 'Pioneer AI image generator famous for perfect text rendering, logos, and graphic design.',
    longDescription: 'Ideogram 2.0 excels at integrating clear typography, logo design, poster layouts, and crisp vector art with unprecedented text accuracy.',
    pricing: 'Free Credits',
    pricingDetail: '10 free prompt generation credits daily',
    url: 'https://ideogram.ai',
    features: ['Typography & text in images', 'Logo design', 'Graphic poster creator', 'Multiple styles'],
    isFeatured: true,
    rating: 4.9,
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo AI',
    category: 'image',
    shortDescription: 'Feature-packed studio for game assets, illustrations, 3D textures, and concept art.',
    longDescription: 'Leonardo AI provides fine-tuned custom models, canvas inpainting, prompt magic, and photo-real engines for creative professionals.',
    pricing: 'Free Credits',
    pricingDetail: '150 daily recurring token allowance',
    url: 'https://leonardo.ai',
    features: ['Artistic control', 'Canvas editor', '150 daily credits', 'Game asset generator'],
    isFeatured: false,
    rating: 4.8,
  },
  {
    id: 'canva-ai-image',
    name: 'Canva AI Image Generator',
    category: 'image',
    shortDescription: 'Convert written thoughts into graphic elements and images inside your Canva projects.',
    longDescription: 'Canva Magic Media empowers users to craft custom illustrations, 3D graphics, watermarks, and photo assets on the fly.',
    pricing: 'Free Plan',
    pricingDetail: 'Included free in basic Canva account',
    url: 'https://www.canva.com/ai-image-generator/',
    features: ['Design integration', 'Style filters', 'Easy export', 'Beginner friendly'],
    isFeatured: false,
    rating: 4.7,
  },
  {
    id: 'microsoft-designer',
    name: 'Microsoft Designer Image Creator',
    category: 'image',
    shortDescription: 'Free DALL-E 3 powered image creator with social media graphic templates.',
    longDescription: 'Microsoft Designer combines AI image generation with smart template layouts, social post dimensions, and instant sticker creation.',
    pricing: 'Free Plan',
    pricingDetail: 'Free with Microsoft account',
    url: 'https://designer.microsoft.com/image-creator',
    features: ['100% Free', 'DALL-E 3 engine', 'Social media templates', 'Sticker generator'],
    isFeatured: false,
    rating: 4.7,
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    category: 'image',
    shortDescription: 'Commercially safe AI graphics model with generative fill, vector expansion, and text effects.',
    longDescription: 'Adobe Firefly is designed to be safe for commercial use, trained on licensed images, offering generative fill and precision adjustments.',
    pricing: 'Free Credits',
    pricingDetail: '25 free monthly generative credits',
    url: 'https://firefly.adobe.com',
    features: ['Generative fill', 'Text effects', 'Vector graphic AI', 'Commercially safe'],
    isFeatured: false,
    rating: 4.8,
  },

  // --- AI WRITING TOOLS ---
  {
    id: 'chatgpt-writing',
    name: 'ChatGPT',
    category: 'writing',
    shortDescription: 'World leading conversational AI for drafting articles, emails, research, and coding.',
    longDescription: 'OpenAI ChatGPT assists in writing essays, summarizing lengthy documents, writing emails, coding, and brainstorming ideas in seconds.',
    pricing: 'Free Plan',
    pricingDetail: 'Free access to GPT-4o mini and standard model',
    url: 'https://chatgpt.com',
    features: ['Drafting & copywriting', 'Document summaries', 'Idea brainstorming', 'Code assistant'],
    isFeatured: true,
    rating: 4.9,
  },
  {
    id: 'google-gemini-writing',
    name: 'Google Gemini',
    category: 'writing',
    shortDescription: 'Google smart AI assistant connected directly to real-time Google search info.',
    longDescription: 'Gemini excels at structured analysis, language translation, creative writing, Google Workspace integration, and quick problem solving.',
    pricing: 'Free Plan',
    pricingDetail: '100% free with unlimited standard responses',
    url: 'https://gemini.google.com',
    features: ['Real-time search info', 'Multilingual writing', 'Google Workspace sync', 'Fast responses'],
    isFeatured: true,
    rating: 4.9,
  },
  {
    id: 'claude-ai',
    name: 'Claude',
    category: 'writing',
    shortDescription: 'Human-like, thoughtful AI writer renowned for long-context analysis and natural tone.',
    longDescription: 'Created by Anthropic, Claude 3.5 Sonnet provides clear, nuanced, and empathetic writing, perfect for long reports and deep analysis.',
    pricing: 'Free Plan',
    pricingDetail: 'Free daily usage on web and mobile app',
    url: 'https://claude.ai',
    features: ['Natural writing tone', 'Long text processing', 'PDF analysis', 'High accuracy'],
    isFeatured: true,
    rating: 4.9,
  },
  {
    id: 'canva-ai-writing',
    name: 'Canva AI Writing',
    category: 'writing',
    shortDescription: 'Magic Write AI assistant for creating blog posts, social captions, and copy.',
    longDescription: 'Magic Write assists you in transforming outline ideas into polished social media captions, headlines, newsletters, and presentation text.',
    pricing: 'Free Plan',
    pricingDetail: '50 free queries per month for free members',
    url: 'https://www.canva.com/magic-write/',
    features: ['Magic Write copy', 'Blog post outlines', 'Social media captions', 'Tone switcher'],
    isFeatured: false,
    rating: 4.7,
  },
];

export const INITIAL_ISLAMIC_BOOKS: IslamicBook[] = [
  {
    id: 'book-1',
    title: 'Fortress of the Muslim (Hisn al-Muslim)',
    author: 'Sa\'id bin \'Ali bin Wahf Al-Qahtani',
    category: 'Duas & Supplications',
    pages: '240',
    fileSize: '3.2 MB',
    pdfUrl: 'https://www.kalamullah.com/Books/Fortress_of_the_Muslim.pdf',
    description: 'The famous collection of authentic daily supplications, dhikr, and prayers from Quran and Sunnah for every occasion.',
    coverColor: 'from-emerald-900 to-green-950',
    icon: '🤲',
    downloadCount: 14200,
  },
  {
    id: 'book-2',
    title: 'Riyad as-Salihin (Gardens of the Righteous)',
    author: 'Imam Abu Zakariya Yahya Al-Nawawi',
    category: 'Hadith & Guidance',
    pages: '680',
    fileSize: '8.5 MB',
    pdfUrl: 'https://www.kalamullah.com/Books/Riyad_us_Saliheen.pdf',
    description: 'A comprehensive compilation of essential Hadiths covering morality, worship, character, manners, and daily spiritual etiquette.',
    coverColor: 'from-amber-900 to-emerald-950',
    icon: '📖',
    downloadCount: 9800,
  },
  {
    id: 'book-3',
    title: 'The Sealed Nectar (Ar-Raheeq Al-Makhtum)',
    author: 'Safiur-Rahman Mubarakpuri',
    category: 'Seerah (Prophetic Biography)',
    pages: '512',
    fileSize: '6.1 MB',
    pdfUrl: 'https://www.kalamullah.com/Books/Ar-Raheeq_Al-Makhtum.pdf',
    description: 'Award-winning biography of Prophet Muhammad (ﷺ), detailing his blessed life, noble character, and timeless teachings.',
    coverColor: 'from-emerald-950 to-amber-950',
    icon: '🌟',
    downloadCount: 18500,
  },
  {
    id: 'book-4',
    title: 'Tajweed Rules for the Qur\'an',
    author: 'Kareema Carol Czerepinski',
    category: 'Quranic Studies',
    pages: '115',
    fileSize: '4.8 MB',
    pdfUrl: 'https://www.kalamullah.com/Books/Tajweed_Rules_Of_The_Quran_Part_1.pdf',
    description: 'Clear, illustrated guide for beginners learning correct pronunciation and Tajweed rules of the Holy Qur\'an.',
    coverColor: 'from-green-900 to-emerald-900',
    icon: '🎙️',
    downloadCount: 7300,
  },
  {
    id: 'book-5',
    title: 'A Brief Illustrated Guide To Understanding Islam',
    author: 'I. A. Ibrahim',
    category: 'Beginner & Intro',
    pages: '74',
    fileSize: '2.9 MB',
    pdfUrl: 'https://www.islam-guide.com/islam-guide.pdf',
    description: 'Easy-to-read introductory book explaining the basic pillars of Islam, scientific miracles in the Quran, and core beliefs.',
    coverColor: 'from-emerald-800 to-green-900',
    icon: '💡',
    downloadCount: 11200,
  },
];

export const INITIAL_QURAN_RESOURCES: QuranResource[] = [
  {
    id: 'quran-com',
    title: 'Quran.com',
    type: 'Interactive Quran Platform',
    url: 'https://quran.com',
    description: 'Read, study, and listen to the Holy Quran with translations in 50+ languages, verse-by-verse audio recitations, and word-by-word analysis.',
    featureTags: ['Translations', 'Audio Recitations', 'Tafsir', 'Search'],
    icon: '📖',
  },
  {
    id: 'quranic-audio',
    title: 'EveryAyah & Quran Audio Explorer',
    type: 'Audio Recitation Library',
    url: 'https://everyayah.com',
    description: 'Stream or download high-quality verse-by-verse Quran recitations by world renowned Qaris including Mishary Rashid, Al-Sudais, and Al-Muaiqly.',
    featureTags: ['Audio Downloads', 'Verse Sync', 'Multiple Qaris', 'High Quality'],
    icon: '🎧',
  },
  {
    id: 'tafsir-app',
    title: 'Tafsir Ibn Kathir Online',
    type: 'Quranic Explanation & Commentary',
    url: 'https://www.quran411.com/tafsir-ibn-kathir',
    description: 'Access the classical commentary of Ibn Kathir for every Surah with clear English explanations and cross-referenced Hadith.',
    featureTags: ['Tafsir', 'Classical Explanation', 'Context of Revelation'],
    icon: '📜',
  },
  {
    id: 'sunnah-com',
    title: 'Sunnah.com Hadith Database',
    type: 'Hadith Reference',
    url: 'https://sunnah.com',
    description: 'Searchable collection of authentic Hadith books including Sahih al-Bukhari, Sahih Muslim, Sunan an-Nasa\'i, and Abu Dawud with gradings.',
    featureTags: ['Sahih Hadith', 'Searchable', 'Gradings', 'Cross-Reference'],
    icon: '📚',
  },
];

export const INITIAL_DUAS: DuaItem[] = [
  {
    id: 'dua-1',
    title: 'Ayat al-Kursi (The Verse of the Throne)',
    category: 'Protection & Safety',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ',
    transliteration: 'Allahu la ilaha illa Huwa, Al-Hayyul-Qayyum. La ta\'khudhuhu sinatun wa la nawm. Lahu ma fis-samawati wa ma fil-ard.',
    english: 'Allah - there is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth.',
    virtue: 'Reciting after each obligatory prayer brings protection and is a gateway to Paradise.',
    reference: 'Surah Al-Baqarah 2:255',
  },
  {
    id: 'dua-2',
    title: 'Dua for Seeking Knowledge',
    category: 'Daily Life',
    arabic: 'رَّبِّ زِدْنِي عِلْمًا',
    transliteration: 'Rabbi zidni \'ilma.',
    english: 'O my Lord, increase me in knowledge.',
    virtue: 'Direct supplication commanded by Allah in the Quran to increase beneficial knowledge.',
    reference: 'Surah Taha 20:114',
  },
  {
    id: 'dua-3',
    title: 'Dua for Ease & Removal of Difficulty',
    category: 'Daily Life',
    arabic: 'اللَّهُمَّ لَا سَهْلَ إِلاَّ مَا جَعَلْتَهُ سَهْلاً، وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلاً',
    transliteration: 'Allahumma la sahla illa ma ja\'altahu sahla, wa anta taj\'alul-hazna idha shi\'ta sahla.',
    english: 'O Allah, there is no ease except in that which You have made easy, and You make difficulty easy if it be Your Will.',
    virtue: 'Relieves anxiety and makes difficult exams, decisions, or work tasks smooth.',
    reference: 'Hisn al-Muslim (Ibn Hibban)',
  },
  {
    id: 'dua-4',
    title: 'Morning & Evening Protection Supplication',
    category: 'Morning & Evening',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Bismillahil-ladhi la yadurru ma\'as-mihi shay\'un fil-ardi wa la fis-sama\'i wa Huwas-Sami\'ul-\'Alim.',
    english: 'In the Name of Allah, with Whose Name nothing on earth or in heaven can cause harm, and He is the All-Hearing, the All-Knowing.',
    virtue: 'Recited 3 times every morning and evening for total divine protection against sudden affliction.',
    reference: 'Sunan Abu Dawud & At-Tirmidhi',
  },
  {
    id: 'dua-5',
    title: 'Dua for Forgiveness & Parents',
    category: 'Praise & Gratitude',
    arabic: 'رَبَّنَا اغْفِرْ لِي وَلِوَالِدَيَّ وَلِلْمُؤْمِنِينَ يَوْمَ يَقُومُ الْحِسَابُ',
    transliteration: 'Rabbana-ghfir li wa li-walidayya wa lil-mu\'minina Yawma yaqumul-hisab.',
    english: 'Our Lord, forgive me and my parents and the believers the Day the account is established.',
    virtue: 'Comprehensive prayer taught by Prophet Ibrahim (AS) for mercy on self, family, and community.',
    reference: 'Surah Ibrahim 14:41',
  },
];

export const INITIAL_ARTICLES: IslamicArticle[] = [
  {
    id: 'article-1',
    title: 'AI Technology & Islamic Ethics: Using Digital Tools Responsibly',
    category: 'Technology & Faith',
    author: 'IS AI Hub Editorial',
    readTime: '4 min read',
    summary: 'How Muslims can leverage AI productivity tools while upholding truthfulness, integrity, and Islamic moral boundaries.',
    content: 'Artificial Intelligence is a powerful tool bestowed by Allah\'s gift of human intellect. In Islam, every tool is judged by its intent and usage. When using AI for writing, image creation, or research, Muslims should adhere to core values: honesty (avoiding deceptive deepfakes or false claims), gratitude (using technology for beneficial knowledge), and balance (not letting screen time distract from obligatory prayers and family time).',
    date: '2026-08-01',
  },
  {
    id: 'article-2',
    title: 'Halal Productivity: 5 Morning Habits for Digital Professionals',
    category: 'Productivity',
    author: 'IS AI Hub Staff',
    readTime: '3 min read',
    summary: 'Transform your morning routine by integrating Fajr prayer, morning Dhikr, and focused deep work blocks.',
    content: 'Barakah (divine blessing in time) begins early in the morning. Prophet Muhammad (ﷺ) prayed: "O Allah, bless my nation in its early hours." By waking up for Fajr, engaging in 10 minutes of morning Azkar, and setting clear daily intentions before opening emails, professionals experience higher focus and peace of mind.',
    date: '2026-07-28',
  },
  {
    id: 'article-3',
    title: 'Understanding the Quran with Modern AI Translation Assistants',
    category: 'Quranic Learning',
    author: 'Dr. Ahmad Hassan',
    readTime: '5 min read',
    summary: 'A guide on using AI tools safely alongside traditional scholar commentary to study Quranic vocabulary and context.',
    content: 'AI language models can break down Arabic root words, grammar structures, and vocabulary instantly. However, AI should be treated as a study aid, not a religious authority. Always cross-reference AI explanations with trusted classical Tafsir works like Ibn Kathir or Ma\'ariful Quran.',
    date: '2026-07-20',
  },
];

export const INITIAL_PROMPTS: PromptItem[] = [
  // Video Prompts
  {
    id: 'prompt-video-1',
    title: 'Cinematic Sunset Mosque Drone Shot',
    category: 'video',
    targetTool: 'Google Veo / Runway / Luma',
    promptText: 'Cinematic 4K aerial drone shot orbiting a magnificent white marble mosque with golden domes at golden hour sunset, soft ambient light reflections on tranquil water courtyard, hyper-realistic, 60fps, slow smooth motion.',
    tags: ['Cinematic', 'Architecture', 'Sunset', 'Drone'],
  },
  {
    id: 'prompt-video-2',
    title: 'Hyper-Realistic Nature Time-lapse',
    category: 'video',
    targetTool: 'Pika / Kling AI',
    promptText: 'Time-lapse video of morning mist rising over lush green pine forest mountains as golden sunlight breaks through the clouds, dew sparkling on autumn leaves, hyper-detailed photorealism.',
    tags: ['Nature', 'Time-lapse', '4K', 'Relaxing'],
  },
  {
    id: 'prompt-video-3',
    title: '3D Animated Islamic History Scene',
    category: 'video',
    targetTool: 'Luma Dream Machine / Runway',
    promptText: 'Beautiful Pixar-style 3D animation of an ancient Islamic library in Baghdad, scholars reading illuminated manuscripts surrounded by warm lantern light, gentle floating dust particles, vibrant cozy atmosphere.',
    tags: ['3D Animation', 'History', 'Pixar Style'],
  },

  // Image Prompts
  {
    id: 'prompt-image-1',
    title: 'Golden Geometric Islamic Art Pattern',
    category: 'image',
    targetTool: 'Ideogram / ChatGPT DALL-E / Gemini',
    promptText: 'Intricate golden Islamic geometric arabesque pattern on deep emerald green velvet background, 3D embossed metallic gold trim, subtle ambient backlight glow, ultra detailed 8k render.',
    tags: ['Geometric', 'Gold & Emerald', 'Wallpaper'],
  },
  {
    id: 'prompt-image-2',
    title: 'Illuminated Quranic Calligraphy Poster',
    category: 'image',
    targetTool: 'Ideogram / Midjourney',
    promptText: 'An elegant typography poster featuring the text "IS AI HUB" rendered in golden modern calligraphy, framed by ornate Andalusian arches, soft volumetric lighting, studio photo style.',
    tags: ['Calligraphy', 'Typography', 'Gold Accent'],
  },
  {
    id: 'prompt-image-3',
    title: 'Halal Modern Tech Workplace',
    category: 'image',
    targetTool: 'ChatGPT / Leonardo AI',
    promptText: 'Clean modern workspace desk with sleek laptop displaying AI data graphs, a hot cup of tea, leather notebook, subtle brass crescent ornament, warm natural morning window light, high aesthetic photography.',
    tags: ['Productivity', 'Minimalist', 'Workplace'],
  },

  // Business Prompts
  {
    id: 'prompt-business-1',
    title: 'Professional B2B Email Outreach',
    category: 'business',
    targetTool: 'ChatGPT / Gemini / Claude',
    promptText: 'Act as a professional B2B marketing consultant. Draft a polite, high-converting cold email template proposing an AI software partnership. Keep the tone warm, concise, professional, and value-focused under 150 words.',
    tags: ['Email', 'Outreach', 'Partnerships'],
  },
  {
    id: 'prompt-business-2',
    title: 'Halal Business Plan Executive Summary',
    category: 'business',
    targetTool: 'ChatGPT / Claude',
    promptText: 'Write a compelling executive summary for an ethical, community-focused digital educational platform. Outline value proposition, revenue streams, target audience, and ethical guidelines emphasizing transparency.',
    tags: ['Business Plan', 'Startup', 'Strategy'],
  },
  {
    id: 'prompt-business-3',
    title: 'Social Media Content Calendar Strategy',
    category: 'business',
    targetTool: 'Gemini / Canva AI',
    promptText: 'Create a 1-week social media content planner for an AI resource directory. Include post ideas for Monday (AI tool spotlight), Wednesday (Prompt tip), Friday (Productivity & faith tip), and Sunday (Resource recap).',
    tags: ['Social Media', 'Marketing', 'Planning'],
  },
];

export const INITIAL_QURAN_VIDEOS: QuranVideoRecitation[] = [
  {
    id: 'vid-1',
    title: 'Surah Ar-Rahman - Heart Soothing Recitation',
    reciter: 'Mishary Rashid Alafasy',
    surah: 'Surah Ar-Rahman (55)',
    duration: '14:20',
    youtubeEmbedUrl: 'https://www.youtube-nocookie.com/embed/28rI3S9eY_4',
    videoUrl: 'https://www.youtube.com/watch?i=28rI3S9eY_4',
    description: 'Soul-stirring visual recitation with English translation subtitles and HD nature imagery.',
    thumbnailIcon: '🎥',
  },
  {
    id: 'vid-2',
    title: 'Surah Al-Mulk - Daily Night Protection',
    reciter: 'Abdul Rahman Al-Sudais',
    surah: 'Surah Al-Mulk (67)',
    duration: '09:45',
    youtubeEmbedUrl: 'https://www.youtube-nocookie.com/embed/pE9q28W69kY',
    videoUrl: 'https://www.youtube.com/watch?v=pE9q28W69kY',
    description: 'Beautiful night recitation with clear line-by-line Arabic script and English translation.',
    thumbnailIcon: '🌌',
  },
  {
    id: 'vid-3',
    title: 'Surah Yasin - Heart of the Quran',
    reciter: 'Maher Al-Muaiqly',
    surah: 'Surah Yasin (36)',
    duration: '18:30',
    youtubeEmbedUrl: 'https://www.youtube-nocookie.com/embed/5UfXv4L_L2M',
    videoUrl: 'https://www.youtube.com/watch?v=5UfXv4L_L2M',
    description: 'Emotional HD video recitation recorded live inside Masjid al-Haram, Makkah.',
    thumbnailIcon: '🕌',
  },
  {
    id: 'vid-4',
    title: 'Surah Al-Kahf - Friday Special Recitation',
    reciter: 'Yasser Al-Dosari',
    surah: 'Surah Al-Kahf (18)',
    duration: '28:15',
    youtubeEmbedUrl: 'https://www.youtube-nocookie.com/embed/8vR4uWq7DDA',
    videoUrl: 'https://www.youtube.com/watch?v=8vR4uWq7DDA',
    description: 'Powerful Friday recitation with English translation and Tajweed color guidance.',
    thumbnailIcon: '✨',
  },
];
